TASK: "realtime"
DEVICE: "cuda:0"

RPPG_MODEL:
  NAME: "FCAtt_v2"
  FRAMES: 128
  FPS: 30
  INPUT_SIZE: 72
  FREQ_ATT_POOL_SIZE: 8
  FREQ_ATT_SHARPNESS: 10.0
  WEIGHTS: "checkpoints/rppg_semi/rppg_fcatt_v2_128f_72px_best.pth"

INFERENCE:
  FACE_CONFIDENCE_THRESHOLD: 0.4
  USE_FP16: false
  WEBCAM_ID: 0
  WEBCAM_W: 640
  WEBCAM_H: 480
  RPPG_BUFFER_SIZE: 128
  RPPG_PREDICT_INTERVAL: 30
  TARGET_FPS: 60
  DISPLAY_WINDOW: true
  SAVE_VIDEO: ""

RPPG_DATA:
  FS: 30
  LARGE_BOX_COEF: 1.5
