TASK: "rppg"
DEVICE: "cuda:0"
NUM_WORKERS: 8

RPPG_MODEL:
  NAME: "FCAtt"
  FRAMES: 128
  FPS: 30
  INPUT_SIZE: 72
  DROP_RATE1: 0.1
  DROP_RATE2: 0.2
  FREQ_ATT_POOL_SIZE: 18
  FREQ_ATT_TEMPORAL_KERNEL: 7
  FREQ_LOW: 0.7
  FREQ_HIGH: 2.5
  SPO2_OFFSET: 80.0
  WEIGHTS: ""

RPPG_DATA:
  DATASET: "PURE"
  DATA_PATH: "D:/PURE"
  CACHED_PATH: "D:/PreprocessedData"
  FS: 30
  CHUNK_LENGTH: 128
  LABEL_TYPE: "DiffNormalized"
  DATA_TYPE: "DiffNormalized"
  CROP_FACE: true
  LARGE_BOX_COEF: 1.5
  RESIZE_W: 72
  RESIZE_H: 72
  DO_PREPROCESS: false
  TEST_DATASET: "UBFC"
  TEST_DATA_PATH: "D:/UBFC/DATASET_2"
  TEST_CACHED_PATH: "D:/PreprocessedData_UBFC"
  TRAIN_BEGIN: 0.0
  TRAIN_END: 0.8
  VALID_BEGIN: 0.7
  VALID_END: 0.9
  TEST_BEGIN: 0.0
  TEST_END: 1.0

RPPG_TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 50
  LR: 0.009
  PRETRAIN_RATIO: 0.6
  GRAD_ACCUMULATION: 4
  GRAD_CLIP: 1.0
  PATIENCE_BVP: 30
  PATIENCE_SPO2: 20
  USE_LAST_EPOCH: false

OUTPUT:
  CHECKPOINT_DIR: "checkpoints/rppg"
  LOG_DIR: "logs/rppg"
